-- Contexto e segurança
USE ROLE ACCOUNTADMIN;

-- 1) Database e schemas principais
CREATE OR REPLACE DATABASE DEMO_DB COMMENT='Demo completo Snowflake';
CREATE OR REPLACE SCHEMA DEMO_DB.RAW;
CREATE OR REPLACE SCHEMA DEMO_DB.STAGE;
CREATE OR REPLACE SCHEMA DEMO_DB.CURATED;
CREATE OR REPLACE SCHEMA DEMO_DB.OPS; -- objetos operacionais (pipes, tasks, procedures, dq)

-- 2) Warehouses (dev/etl/bi) com politicas de economia
CREATE OR REPLACE WAREHOUSE WH_DEV
  WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Desenvolvimento';

CREATE OR REPLACE WAREHOUSE WH_ETL
  WITH WAREHOUSE_SIZE='SMALL' AUTO_SUSPEND=120 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Ingestão e Transformações';

CREATE OR REPLACE WAREHOUSE WH_BI
  WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE COMMENT='Consumo BI';

-- 3) Resource Monitor (FinOps)
-- Ajuste créditos conforme sua política; 100 créditos/mês como exemplo
CREATE OR REPLACE RESOURCE MONITOR RM_MONTHLY
  WITH CREDIT_QUOTA=100 FREQUENCY=MONTHLY START_TIMESTAMP=IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 90 PERCENT DO SUSPEND
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE WH_DEV SET RESOURCE_MONITOR = RM_MONTHLY;
ALTER WAREHOUSE WH_ETL SET RESOURCE_MONITOR = RM_MONTHLY;
ALTER WAREHOUSE WH_BI  SET RESOURCE_MONITOR = RM_MONTHLY;

-- 4) Visões de custo/uso (FinOps)
USE DATABASE DEMO_DB;
USE SCHEMA OPS;

CREATE OR REPLACE VIEW VW_WAREHOUSE_CREDITS AS
SELECT
  WAREHOUSE_NAME,
  START_TIME,
  END_TIME,
  CREDITS_USED,
  CREDITS_USED_COMPUTE,
  CREDITS_USED_CLOUD_SERVICES,
  DATE_TRUNC('day', START_TIME) AS USAGE_DAY
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
ORDER BY START_TIME DESC;

CREATE OR REPLACE VIEW VW_STORAGE_USAGE_DAILY AS
SELECT
  USAGE_DATE,
  STORAGE_BYTES,
  STAGE_BYTES,
  FAILSAFE_BYTES
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
ORDER BY USAGE_DATE DESC;

-- 5) Contexto padrão para próximos scripts
USE WAREHOUSE WH_DEV;
USE SCHEMA DEMO_DB.RAW;
