USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_DB;
USE SCHEMA OPS;

-- 1) Formatos de arquivo
CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE=CSV FIELD_DELIMITER=',' SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('\\N','NULL','null','');

CREATE OR REPLACE FILE FORMAT FF_JSON TYPE=JSON;
CREATE OR REPLACE FILE FORMAT FF_PARQUET TYPE=PARQUET;

-- 2) Integração de armazenamento (S3)
-- Substitua pelos valores corretos do seu ambiente
CREATE OR REPLACE STORAGE INTEGRATION SI_S3_DEMO
  TYPE=EXTERNAL_STAGE
  STORAGE_PROVIDER=S3
  ENABLED=TRUE
  STORAGE_AWS_ROLE_ARN='<AWS_ROLE_ARN>'
  STORAGE_ALLOWED_LOCATIONS=('s3://<BUCKET_NAME>/<PREFIX>/');

-- Verifique as instruções geradas para confiar na role no seu ambiente AWS
DESC INTEGRATION SI_S3_DEMO;

-- 3) Stage externo (S3) e interno
CREATE OR REPLACE STAGE DEMO_DB.RAW.STG_S3
  STORAGE_INTEGRATION=SI_S3_DEMO
  URL='s3://<BUCKET_NAME>/<PREFIX>/'
  FILE_FORMAT=FF_CSV;

CREATE OR REPLACE STAGE DEMO_DB.RAW.STG_INTERNAL
  FILE_FORMAT=FF_CSV;

-- 4) Tabelas de exemplo (landing)
USE SCHEMA DEMO_DB.RAW;
CREATE OR REPLACE TABLE CUSTOMERS_RAW (
  ID STRING,
  NAME STRING,
  EMAIL STRING,
  COUNTRY STRING,
  UPDATED_AT TIMESTAMP_NTZ
);

-- Exemplo de COPY (manual)
-- COPY INTO CUSTOMERS_RAW
--   FROM @DEMO_DB.RAW.STG_S3
--   FILE_FORMAT=(FORMAT_NAME=DEMO_DB.OPS.FF_CSV)
--   PATTERN='.*customers.*.csv'
--   ON_ERROR='CONTINUE';
