USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_DB;
USE SCHEMA OPS;

-- 1) Notification Integration (S3 → Snowpipe)
-- Configure no AWS: S3 Event -> SNS -> SQS. Use o ARN abaixo.
CREATE OR REPLACE NOTIFICATION INTEGRATION NI_S3_DEMO
  TYPE=QUEUE
  ENABLED=TRUE
  NOTIFICATION_PROVIDER=AWS_SQS
  AWS_SQS_ARN='<AWS_SQS_ARN>'
  AWS_SNS_TOPIC_ARN='<AWS_SNS_TOPIC_ARN>'
  -- opcional: usar apenas SQS dependendo da sua arquitetura
  COMMENT='Integração para Snowpipe demo S3';

DESC INTEGRATION NI_S3_DEMO;

-- 2) Pipe (auto_ingest)
USE SCHEMA DEMO_DB.RAW;
CREATE OR REPLACE PIPE PIPE_CUSTOMERS_RAW
  AUTO_INGEST=TRUE
  INTEGRATION=DEMO_DB.OPS.NI_S3_DEMO
  AS
COPY INTO DEMO_DB.RAW.CUSTOMERS_RAW
FROM @DEMO_DB.RAW.STG_S3
FILE_FORMAT=(FORMAT_NAME=DEMO_DB.OPS.FF_CSV)
PATTERN='.*customers.*.csv'
ON_ERROR='CONTINUE';

-- 3) Testes e operações
-- ALTER PIPE DEMO_DB.RAW.PIPE_CUSTOMERS_RAW REFRESH; -- para (re)varrer objetos existentes
-- SELECT SYSTEM$PIPE_STATUS('DEMO_DB.RAW.PIPE_CUSTOMERS_RAW');
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME=>'DEMO_DB.RAW.CUSTOMERS_RAW', START_TIME=>DATEADD('day',-1,CURRENT_TIMESTAMP())));
