USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_DB;

-- 1) Views seguras para BI
CREATE OR REPLACE SECURE VIEW DEMO_DB.CURATED.VW_CUSTOMERS AS
SELECT CUSTOMER_KEY, ID, NAME, EMAIL, COUNTRY, UPDATED_AT
FROM DEMO_DB.CURATED.DIM_CUSTOMER;

CREATE OR REPLACE VIEW DEMO_DB.CURATED.VW_COUNTRY_METRICS AS
SELECT COUNTRY, NUM_CUSTOMERS
FROM DEMO_DB.CURATED.DT_COUNTRY_CUSTOMERS;

-- 2) Procedure para refresh manual (útil para BI on-demand)
CREATE OR REPLACE PROCEDURE DEMO_DB.OPS.REFRESH_CURATED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  ALTER TASK DEMO_DB.OPS.T_RAW_TO_STAGE EXECUTE IMMEDIATELY;
  ALTER TASK DEMO_DB.OPS.T_STAGE_TO_CURATED EXECUTE IMMEDIATELY;
  RETURN 'Triggered refresh tasks.';
END;
$$;

-- 3) Schedule específico para consumo (ex.: BI downstream)
CREATE OR REPLACE TASK DEMO_DB.OPS.T_REFRESH_DASHBOARDS
  WAREHOUSE=WH_BI
  SCHEDULE='USING CRON 0 6 * * * UTC' -- 06:00 UTC
AS
CALL DEMO_DB.OPS.REFRESH_CURATED();

ALTER TASK DEMO_DB.OPS.T_REFRESH_DASHBOARDS RESUME;

-- Notas Power BI: use o conector Snowflake, aponte para VW_CUSTOMERS/VW_COUNTRY_METRICS com ROLE de leitura.
