USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_DB;

-- 1) Stream operacional na STAGE para identificar mudanças
CREATE OR REPLACE STREAM DEMO_DB.STAGE.STREAM_CUSTOMERS_STAGE ON TABLE DEMO_DB.STAGE.CUSTOMERS_STAGE;

-- 2) Tabela operacional para auditoria
CREATE OR REPLACE SCHEMA DEMO_DB.OPS;
CREATE OR REPLACE TABLE DEMO_DB.OPS.OP_CUSTOMER_CHANGES (
  CHANGE_TIME TIMESTAMP_NTZ,
  CHANGE_TYPE STRING,
  ID NUMBER,
  NAME STRING,
  EMAIL STRING,
  COUNTRY STRING
);

-- 3) Task que captura mudanças de forma contínua (quase streaming)
CREATE OR REPLACE TASK DEMO_DB.OPS.T_CAPTURE_CHANGES
  WAREHOUSE=WH_ETL
  SCHEDULE='1 minute'
AS
INSERT INTO DEMO_DB.OPS.OP_CUSTOMER_CHANGES
SELECT CURRENT_TIMESTAMP(), METADATA$ACTION, ID, NAME, EMAIL, COUNTRY
FROM DEMO_DB.STAGE.STREAM_CUSTOMERS_STAGE
WHERE METADATA$ISUPDATE = 'TRUE' OR METADATA$ACTION IN ('INSERT','DELETE');

ALTER TASK DEMO_DB.OPS.T_CAPTURE_CHANGES RESUME;

-- Notas:
-- Para latência menor e ingestão near-real-time, avalie Snowpipe Streaming ou Kafka Connector.
-- Streams + Tasks fornecem visão operacional com baixa complexidade para muitos casos.
