USE ROLE ACCOUNTADMIN;

-- 1) Roles e Grants
CREATE OR REPLACE ROLE DEMO_ADMIN;
CREATE OR REPLACE ROLE DEMO_ETL;
CREATE OR REPLACE ROLE DEMO_BI;

GRANT ROLE DEMO_ADMIN TO ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE DEMO_ETL;
GRANT USAGE ON WAREHOUSE WH_ETL TO ROLE DEMO_ETL;
GRANT USAGE ON WAREHOUSE WH_BI  TO ROLE DEMO_BI;

GRANT USAGE ON DATABASE DEMO_DB TO ROLE DEMO_ETL, ROLE DEMO_BI;
GRANT USAGE ON SCHEMA DEMO_DB.RAW TO ROLE DEMO_ETL;
GRANT USAGE ON SCHEMA DEMO_DB.STAGE TO ROLE DEMO_ETL;
GRANT USAGE ON SCHEMA DEMO_DB.CURATED TO ROLE DEMO_ETL, ROLE DEMO_BI;
GRANT USAGE ON SCHEMA DEMO_DB.OPS TO ROLE DEMO_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEMO_DB.RAW TO ROLE DEMO_ETL;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEMO_DB.STAGE TO ROLE DEMO_ETL;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DB.CURATED TO ROLE DEMO_BI;
GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DB.CURATED TO ROLE DEMO_BI;

-- 2) Tags e classificação
CREATE OR REPLACE TAG TAG_SENSITIVITY ALLOWED_VALUES ('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED');
ALTER TABLE DEMO_DB.CURATED.DIM_CUSTOMER SET TAG TAG_SENSITIVITY = 'INTERNAL';
ALTER TABLE DEMO_DB.CURATED.DIM_CUSTOMER MODIFY COLUMN EMAIL SET TAG TAG_SENSITIVITY = 'CONFIDENTIAL';

-- 3) Masking Policy para EMAIL
CREATE OR REPLACE MASKING POLICY MP_MASK_EMAIL AS (VAL STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','DEMO_ADMIN') THEN VAL
    ELSE REGEXP_REPLACE(VAL, '(^.).*(@.*$)', '\\1***\\2')
  END;

ALTER TABLE DEMO_DB.CURATED.DIM_CUSTOMER MODIFY COLUMN EMAIL SET MASKING POLICY MP_MASK_EMAIL;

-- 4) Row Access Policy por COUNTRY
CREATE OR REPLACE ROW ACCESS POLICY RAP_COUNTRY AS (COUNTRY STRING) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','DEMO_ADMIN') THEN TRUE
    WHEN CURRENT_ROLE() IN ('DEMO_BI') THEN COUNTRY IN ('US','BR','PT')
    ELSE FALSE
  END;

ALTER TABLE DEMO_DB.CURATED.DIM_CUSTOMER ADD ROW ACCESS POLICY RAP_COUNTRY ON (COUNTRY);

-- 5) Network Policy (exemplo de allowlist)
CREATE OR REPLACE NETWORK POLICY NP_ALLOW_CORP
  ALLOWED_IP_LIST = ('<YOUR_OFFICE_IP/CIDR>')
  BLOCKED_IP_LIST = ('0.0.0.0/0');
-- Associe ao usuário/conta conforme necessário
-- ALTER ACCOUNT SET NETWORK_POLICY = NP_ALLOW_CORP;
